config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  resources :meals do
    resources :food_item_meals
  end

  resources :food_items
  # resources :food_item_meals
  # get "new_food_item_meals", to: "meals#new_food_item_meals"
  resources :daily_plans

  root to: "food_items#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_plan.rb
# frozen_string_literal: true

class DailyPlan < ApplicationRecord
  has_many :daily_plan_meals
  has_many :meals, through: :daily_plan_meals
end

app/models/daily_plan_meal.rb
# frozen_string_literal: true

class DailyPlanMeal < ApplicationRecord
  belongs_to :daily_plan
  belongs_to :meal
end

app/models/food_item.rb
# frozen_string_literal: true

class FoodItem < ApplicationRecord
  validates :name, :item_type, presence: true

  enum item_type: %i[protein carb fat vegetable other]

  has_many :food_item_meals
  has_many :meals, through: :food_item_meals
end

app/models/food_item_meal.rb
# frozen_string_literal: true

class FoodItemMeal < ApplicationRecord
  belongs_to :food_item
  belongs_to :meal
end

app/models/meal.rb
# frozen_string_literal: true

# FoodItemCombo == meal
class Meal < ApplicationRecord
  enum name: %i[breakfast lunch dinner]

  has_many :daily_plan_meals
  has_many :daily_plans, through: :daily_plan_meals
  has_many :food_item_meals
  has_many :food_items, through: :food_item_meals

  scope :breakfasts, -> { where(name: names[:breakfast]) }
  scope :lunches, -> { where(name: names[:lunch]) }
  scope :dinners, -> { where(name: names[:dinner]) }
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/food_item_meals_controller.rb
# frozen_string_literal: true

class FoodItemMealsController < ApplicationController
  def new
    @food_item_meal = FoodItemMeal.new
  end

  def create
    @food_item_meal = FoodItemMeal.new(food_item_meal_params)
    respond_to do |format|
      if @food_item_meal.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("meals_list", partial: "food_item_meals/meals_list",
                                                                  locals: { food_item_meal: @food_item_meal })
        end
        # format.html { redirect_to food_item_meal_url(@food_item_meal), notice: "Meal was successfully created." }
        # else
        # format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @food_item_meal.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def food_item_meal_params
    params.require(:food_item_meal).permit(:food_item_id, :meal_id)
  end
end

app/controllers/food_items_controller.rb
# frozen_string_literal: true

class FoodItemsController < ApplicationController
  before_action :set_food_item, only: %i[show edit update destroy]

  def index
    @pantry_items = FoodItem.where(refrigerated: false).order(:name)
    @fridge_items = FoodItem.where(refrigerated: true).order(:name)
    @meals = Meal.all
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  def edit; end

  def create
    @food_item = FoodItem.new(food_item_params)
    respond_to do |format|
      if @food_item.save
        format.turbo_stream do
          section = @food_item.refrigerated? ? "fridge" : "pantry"
          render turbo_stream: turbo_stream.prepend(section, partial: "food_items/food_item",
                                                             locals: { food_item: @food_item, editable: true })
        end
        format.html { redirect_to food_item_url(@food_item), notice: "food item was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@food_item, partial: "food_items/food_item",
                                                                locals: { food_item: @food_item, editable: true })
        end
        format.html { redirect_to food_item_url(@food_item), notice: "food_item was successfully updated." }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_food_item
    @food_item = FoodItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_item_params
    params.require(:food_item).permit(:name, :item_type, :refrigerated, :in_kitchen)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/food_items_helper.rb
# frozen_string_literal: true

module FoodItemsHelper
  def icon(food_item)
    case food_item.item_type_before_type_cast
    when FoodItem.item_types[:vegetable] then "carrot"
    when FoodItem.item_types[:fat] then "cheese"
    when FoodItem.item_types[:protein] then "fish"
    when FoodItem.item_types[:carb] then "bread-slice"
    else
      "utensils"
    end
  end

  def food_item_classes(food_item)
    spacing = " py-1 mb-3 mr-2 flex items-center"
    case food_item.item_type
    when "vegetable" then "bg-lime-500 #{spacing}"
    when "carb" then "bg-yellow-400 #{spacing}"
    when "protein" then "bg-sky-300 #{spacing}"
    when "fat" then "bg-fuchsia-300 #{spacing}"
    else
      "bg-zinc-300 #{spacing}"
    end
  end
end

app/helpers/meals_helper.rb
# frozen_string_literal: true

module MealsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/food_item_meals/_form.html.erb
<%= form_with(url: meal_food_item_meals_path, model: food_item_meal, local: true) do |form| %>
  <% if food_item_meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item_meal.errors.count, "error") %> prohibited this food_item_meal from being saved:</h2>
      <ul>
        <% food_item_meal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.collection_select(:food_item_id, FoodItem.all, :id, :name) %>
    <%= form.hidden_field(:meal_id, value: params[:meal_id]) %>
  </div>
  <div>
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/food_item_meals/_meals_list.html.erb
<h3>Weekly Meals</h3>
<section class='bg-white p-4 h-3/4 overflow-scroll'>
  <div id='meals_list' class='meals-list flex flex-wrap'>
    <% DailyPlan.all.each do |daily_plan|%>
      <div class='meal sm:w-1/2 md:w-1/3 pr-4 pb-8'>
        <h5>
          <%= daily_plan.date.strftime("%A %m/%d/%y") %>
        </h5>
        <div>
          <% daily_plan.meals.each do |meal|%>
            <p class="uppercase"><%= meal.name %></p>
            <%= link_to "+ Add Food", new_meal_food_item_meal_path(meal.id), data: { turbo_frame: 'modal' } %>
            <div class='flex'>
              <% meal.food_items.each do |food_item| %>
                <%= render "food_items/food_item", {food_item: food_item, editable: false} %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/food_item_meals/index.html.erb
<div class='flex flex-col justify-around w-full h-screen p-8'>
  <%= render "food_item_meals/meals_list" %>
  <section class='bg-white p-4 h-1/4 overflow-scroll mt-8'>
    <%= render "kitchen" %>
  </section>
</div>

app/views/food_item_meals/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal", action: "turbo:submit-end->turbo-modal#submitEnd" }, class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
    <h1 class="font-bold text-4xl">New meal</h1>
    <%= render "form", food_item_meal: @food_item_meal %>
    <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
  <% end %>
<% end %>

app/views/food_items/_food_item.html.erb
<div id="<%= dom_id food_item %>" data-sort-target=​"sortElement" data-sort-value=​"​​#{food_item.name}​​">
  <div class="<%=food_item_classes(food_item)%>">
    <%= food_item.name %>
    <div class='mx-2'><%= fa_icon icon(food_item)%></div>
    <% if editable %>
      <%= link_to edit_food_item_path(food_item), data: { turbo_frame: 'modal' } do %>
        <%= fa_icon "edit"%>
      <% end %>
    <% end %>
  </div>
</div>

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>
      <ul>
        <% food_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :item_type %>
    <%= form.select :item_type, options_for_select(FoodItem.item_types.map {|key, value| [key.titleize, FoodItem.item_types.key(value)]}, @food_item.item_type) %>
  </div>
  <div>
    <%= form.label :refrigerated %>
    <%= form.check_box :refrigerated %>
  </div>
  <div>
    <%= form.label :in_kitchen %>
    <%= form.check_box :in_kitchen %>
  </div>
  <div>
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/food_items/_kitchen.erb
<h3>Kitchen Food Items</h3>
<div>
  <%= link_to "New Food", new_food_item_path, data: { turbo_frame: 'modal' } %>
</div>
<div class='flex flex-col'>
  <h5>Pantry</h5>
  <div id="pantry" class='flex flex-wrap'>
    <% @pantry_items.each do |food_item| %>
      <%= render "food_item",{ food_item: food_item, editable: true } %>
    <% end %>
  </div>
</div>
<div  class='flex flex-col'>
  <h5>Fridge</h5>
  <div id="fridge" class='flex flex-wrap'>
    <% @fridge_items.each do |food_item| %>
      <%= render "food_item", { food_item: food_item, editable: true } %>
    <% end %>
  </div>
</div>

app/views/food_items/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal", action: "turbo:submit-end->turbo-modal#submitEnd" }, class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
    <h1 class="font-bold text-4xl">Edit food item</h1>
    <%= render "form", food_item: @food_item %>
    <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
  <% end %>
<% end %>

app/views/food_items/index.html.erb
<div class='flex flex-col justify-around w-full h-screen p-8'>
  <%= render "meals/meals_list" %>
  <section class='bg-white p-4 h-1/4 overflow-scroll mt-8'>
    <%= render "kitchen" %>
  </section>
</div>

app/views/food_items/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal", action: "turbo:submit-end->turbo-modal#submitEnd" }, class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
    <h1 class="font-bold text-4xl">New food_item</h1>
    <%= render "form", food_item: @food_item %>
    <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>What's For Dinner?</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="">
      <%= turbo_frame_tag "modal" %>
      <%= yield %>
    </main>
  </body>
</html>
<%= javascript_include_tag "https://kit.fontawesome.com/62b10ade4b.js"%>

app/views/meals/_meals_list.html.erb
  
<h3>Weekly Meals</h3>
<section class='bg-white p-4 h-3/4 overflow-scroll'>
  <div id='meals_list' class='meals-list flex flex-wrap'>
    <% DailyPlan.all.each do |daily_plan|%>
      <div class='meal sm:w-1/2 md:w-1/3 pr-4 pb-8'>
        <h5>
          <%= daily_plan.date.strftime("%A %m/%d/%y") %>
        </h5>
        <div>
          <% daily_plan.meals.each do |meal|%>
            <p class="uppercase"><%= meal.name %></p>
            <%= link_to "+ Add Food", new_meal_path, data: { turbo_frame: 'modal' } %>
            <div class='flex'>
              <% meal.food_items.each do |food_item| %>
                <%= render "food_item", {food_item: food_item, editable: false} %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/meals/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal", action: "turbo:submit-end->turbo-modal#submitEnd" }, class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
    <h1 class="font-bold text-4xl">New meal</h1>
    <%= render "form", meal: @meal %>
    <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>